export const programs = [
  {
    id: "p1",
    category: "INFRASTRUKTUR",
    title: "Benahi Rumah",
    desc: "Inisiatif komprehensif yang ditujukan untuk merenovasi dan memperbaiki kondisi perumahan bagi keluarga berpenghasilan rendah,...",
    fullDesc: "Program ini bertujuan untuk memberikan kondisi tempat tinggal yang lebih baik bagi mereka yang membutuhkan dengan merenovasi rumah yang strukturnya tidak layak atau kurang sanitasi dasar. Kami bekerja erat dengan kontraktor lokal dan masyarakat untuk memberikan solusi perumahan yang berkualitas tinggi dan berkelanjutan.",
    objectives: ["Penguatan struktural", "Peningkatan sanitasi", "Keterlibatan masyarakat"],
    status: "Berjalan",
    image: "/article-featured.png",
    date: "2024 - Sekarang",
    location: "Jawa Barat",
  },
  {
    id: "p2",
    category: "PENDIDIKAN",
    title: "Penyerahan PIP",
    desc: "Distribusi dana Program Indonesia Pintar (PIP) untuk memastikan setiap anak memiliki akses ke pendidikan yang berkualitas...",
    fullDesc: "Program Indonesia Pintar (PIP) dirancang untuk membantu anak-anak dari keluarga kurang mampu mendapatkan akses ke pendidikan yang berkualitas. Inisiatif ini mendistribusikan dana langsung kepada siswa untuk perlengkapan sekolah, seragam, dan transportasi.",
    objectives: ["Bantuan keuangan untuk siswa", "Mengurangi tingkat putus sekolah", "Meningkatkan kesetaraan pendidikan"],
    status: "Selesai",
    image: "/article-featured.png",
    date: "2023",
    location: "Berbagai Kabupaten",
  },
  {
    id: "p3",
    category: "KESEHATAN",
    title: "Santunan BPJS",
    desc: "Memfasilitasi akses ke manfaat asuransi kesehatan nasional dan memberikan dukungan tambahan bagi keluarga yang menghadapi...",
    fullDesc: "Kami memfasilitasi akses ke asuransi kesehatan nasional (BPJS) bagi mereka yang tidak mengetahui prosesnya atau tidak mampu membayar premi. Dukungan keuangan tambahan juga diberikan bagi keluarga yang menghadapi keadaan darurat medis parah.",
    objectives: ["Aksesibilitas layanan kesehatan", "Dukungan medis darurat", "Pendidikan kesehatan"],
    status: "Berjalan",
    image: "/article-featured.png",
    date: "2023 - Sekarang",
    location: "Jawa Barat",
  },
  {
    id: "p4",
    category: "EKONOMI",
    title: "Bantuan Alat UMKM",
    desc: "Memberdayakan usaha mikro, kecil, dan menengah lokal melalui penyediaan alat-alat esensial,...",
    fullDesc: "Usaha kecil adalah tulang punggung perekonomian kita. Program ini memberdayakan UMKM (Usaha Mikro, Kecil, dan Menengah) lokal dengan menyediakan alat-alat yang diperlukan, peralatan, dan pelatihan untuk mengembangkan bisnis mereka dan menciptakan lebih banyak lapangan kerja.",
    objectives: ["Pertumbuhan bisnis lokal", "Penciptaan lapangan kerja", "Ketahanan ekonomi"],
    status: "Berjalan",
    image: "/article-featured.png",
    date: "2024",
    location: "Jawa Barat",
  },
  {
    id: "p5",
    category: "LINGKUNGAN",
    title: "Komunitas Hijau",
    desc: "Membangun taman kota dan fasilitas pengelolaan sampah untuk mendorong keberlanjutan lingkungan dan ketahanan pa...",
    fullDesc: "Ditujukan untuk membuat kota kita lebih hijau, inisiatif ini membangun kebun perkotaan dan fasilitas pengelolaan limbah modern. Program ini juga berfokus pada pendidikan masyarakat tentang pertanian berkelanjutan dan daur ulang.",
    objectives: ["Pertanian berkelanjutan", "Keterlibatan masyarakat", "Pengurangan limbah"],
    status: "Selesai",
    image: "/article-featured.png",
    date: "2022",
    location: "Bandung",
  },
  {
    id: "p6",
    category: "PENDIDIKAN",
    title: "Literasi Digital",
    desc: "Memberikan pelatihan keterampilan digital dasar untuk semua kelompok umur guna menjembatani kesenjangan digital dan mempersiapkan warga...",
    fullDesc: "Di era digital, literasi digital adalah suatu keharusan. Kami memberikan pelatihan untuk semua kelompok umur, berfokus pada keterampilan komputasi dasar, kesadaran keamanan internet, dan memanfaatkan alat digital untuk pendidikan dan bisnis.",
    objectives: ["Keterampilan komputasi dasar", "Kesadaran keamanan internet", "Inklusi digital"],
    status: "Berjalan",
    image: "/article-featured.png",
    date: "2024 - Sekarang",
    location: "Jawa Barat",
  },
];
